### ISSUE TITLE
CPU temp is not reported correctly

### ISSUE THREAD

**Issue by tb205gti** [BogGyver/openpilot#103]
CPU temps sems to be stuck. Getting cpu temp in UI of 26 deg C - even after driving several kilometers.

**Comment by arne182** [comment]
Reboot and it should be working again

**Comment by tb205gti** [comment]
But why not try and fix the issue rather than just mitigate it?

**Comment by BogGyver** [comment]
something started that in 0.6.3. if still happens in 0.6.4 we need to figure it out. I think it is unfortunately OS related and not OP related.

**Comment by tb205gti** [comment]
Working again in 0.6.6
